--- #YAML:1.0
name:                PerlIO-via-EscStatus
version:             2
abstract:            Printing a status line through an I/O layer.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    PerlIO::via:                   0
    Regexp::Common:                0
    Term::Size:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
no_index:
    directory:
        - devel
resources:
    homepage: http://www.geocities.com/user42_kevin/perlio-via-escstatus/index.html
